apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebooks
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
