apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: job-general
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: ghcr.io/cukhoaimon/spark-job-general:latest
  imagePullPolicy: Always
  imagePullSecrets:
    - ghcr-pull-secret
  mainApplicationFile: local:///opt/spark/jobs/main.py

  sparkVersion: "3.5.3"
  sparkConfigMap: spark-defaults

  sparkConf:
    spark.sql.extensions: "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
    spark.sql.catalog.iceberg: "org.apache.iceberg.spark.SparkCatalog"
    spark.sql.catalog.iceberg.type: "rest"
    spark.sql.catalog.iceberg.uri: "http://iceberg-rest-catalog.data-warehouse.svc.cluster.local:8181"
    spark.sql.catalog.iceberg.warehouse: "s3://warehouse/"
    spark.sql.catalog.iceberg.io-impl: "org.apache.iceberg.aws.s3.S3FileIO"
    spark.sql.catalog.iceberg.s3.endpoint: "http://primary-object-store.data-warehouse.svc.cluster.local:9000"
    spark.sql.catalog.iceberg.s3.path-style-access: "true"
    spark.sql.catalog.iceberg.s3.region: "us-east-1"
    spark.sql.defaultCatalog: "iceberg"

  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-driver
    envFrom:
      - secretRef:
          name: minio-credentials
    env:
      - name: AWS_REGION
        value: us-east-1

  executor:
    cores: 1
    instances: 1
    memory: "512m"
    envFrom:
      - secretRef:
          name: minio-credentials
    env:
      - name: AWS_REGION
        value: us-east-1

  restartPolicy:
    type: OnFailure
    onFailureRetries: 2
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 20
