postgres:
  host: postgresql.shared-services.svc.cluster.local
  port: 5432
  database: iceberg
  user: iceberg
  password: iceberg

catalog:
  warehouse: s3://warehouse/
  s3Endpoint: http://primary-object-store.data-warehouse.svc.cluster.local:9000
  awsRegion: us-east-1
