apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-ivy-cache
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ivyCache.storage }}
