---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: spark
spec:
  encryptedData:
    .dockerconfigjson: AgCHIP0mEh8AIIoF4pxp3FtWATBeRQPGVe3Q4wnY4pJ8EMzL8FBn+R+K5zlzc0QPUflZyE0tQNpCqBJG/oT5K7MzDZYtSYTkrLCqx7oRrepL0LoOvTaLysNJi8z7/PRm6n1ikrgRw50b7GjkHd0lb6xP3rPIMSGI5cybAXT5JQQ3cZlX3Nkr3oO3U/afU4J6pDkutgJEh34zuLJhlbCOJGMrU5ugzAWdRhfOu4OiXeL5qL6xWcymL+CkodXFAMfzNvHv8ykaYu66dkf1zEDOwk6NG5ufG7fap0qPx6K+rYoL8+c5LTLNkxU8uyaCNm/GTMft4r5ZytiVOhdGsGC1QP3PmZDolxW3GPwW4RhuKTFr0iau3h/mJ3JbaR8JgUNFyNABXPeyE7/AcnwX42OmPPnRUI0df7PzTp8QDpa9GRi72A4tB+R8FCUrAbGdIItsT/06+quhKB7sHNEsLnwtK5WM1AGKAmbDvr6gWBDggj85jMcBLl2tn32QUUa8aW2y5621ddiPACrCLzFgLT54p2hpTsxgqeA6utz1HtrTfORUltx2EpsmxOY/OJEGFM7x4YOV50JCoNrOzyhxNh2r5Amsa4nD6aXElnSW5vApkDpHDpFBKpXOIvLl2qGIaUinFZHYlsfdjH5vJT9WrQrkR6gIyi/9QMJYV8MrkICaA/nXP38NB4iYMg64oa1L01KEzFwN2ipx3vltdYpM42j2oL0Fpgq6OaWAx+oJevVlud0snAPCuENp7qJ2M+b0GZViCqKG+EKhB43rqVOiLI6CnBEfHn/nKyE3DwEA7pN91eSHoO37fgUUs4gtRzQ0BnyNlD/zdYBAqUOvu9A4mgsDd+dcVyV9HXWQEQXDPQPJI+ddU17+GvDv6dljse6rnUPSxjivYO429CH5D+XD5IE8Q6fmz2buGz2UF3V51OsKFdupv+WxgQ==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: spark
    type: kubernetes.io/dockerconfigjson
