---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: spark
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBQ23Z3o5ly/klG1Z38cL91KIoNWwtnbtIZ15zqMikdIzNVPihd6DlH+rDxIx39ZFjEjkrMO2mbhuPRa8H7+FsUOTsafPY1NTcSG1tYiXLVw8rvuh+TCL74xc5eQDGi5KFCgSpnf4VzeZZm65mYWMgfYeDps/sR3CHbN48g0/W7hQ6byKKNPMO/7ZbWvspcqCbSjC5yqQBNx9/tskAuP7iXIvk18vSVk/fSfRwQL2ndDS6SAcTPYvlaHYmrAVkp6EmdjWRCNIkiCqRxn06M9SlRpsqYs3se0ZX4NY5job8G6S9FxPL/splODM2rQcXyDpNrXFtiOxZjnxd21WVCf3rseC0hlwmzmIOD8sTf6T2qyhvGRyhOigZEICsJIShf6VxfkpZVRm+qzCCEMkGHsqrrQB+2qtDvplvWFpu656omKI0nbmimxVDD/aWi9qUOoutq+JtJODgjTLyELjA9T+ZF51AL64hvQZCGdmYRO+oDJUpfhh+VyIByz2JjQAzanMcHvgCtG5tpUoGnu3rG3XBU37+M7eNg+Kt5H2EueybOKvP0SB6I3AA05gukzTRJfLl/4hyntOQd9IRZniWdH+wKFQqhLAxwjirG2QgvSxNnTr8cH9KHMHY94PjOCAyZOOkbJaMQIXVfAfJyFmWhPxYlNF8AoHBXJzVAzVXCzej1sv4JZIFR20rVgHYIrla6Z61vbhfVsA==
    AWS_SECRET_ACCESS_KEY: AgBc98jiSmeNUfSFZFN8ib74wrHedv5mz62ez7Jb2j9gj6xqDu97RJ3b7EI6mzj4QzEOZqfeusFRjSRLCaEEtDIe+GG/vofPgo30CRlUAnRL9NAr4mk16F6bgQxG2eTXgwhP81qtHCs99YeA98DjpQYnhFrcAx32tc/kOBDWN9rZjBuXvBeWPQDbcTJUIkxSb6T7ur2x6N0XjywCA59xDYqfcDUsF4wRFlWCh13oFRfrCGVs59sWzVBSV91BaMV6XD5mKRkahoQ3wSGKhNrH3AC1ZMPxDym0vJQ6W3DeNtH+EamhO+cj0sn9SasXzgXSOewJCEPE9QEUnvTxTu08cWsmDe4i3z3FaHOZbyZ8TblD20x0MZUEkJRgaPFX/je68Ftj0IB/lzt5sgEA5Q5czV+zlYWiAK/Omzyr7Qzkz4AnTBEaqcV33xJ9iSQyBBbGg8hF75mlOe8J600/liehMI9j5NqkNk9r8vCaYe2G5oLFOEpLILD7GfoSFa1llg5DYjNYYmNAVHfz9XjtJUPYsNp3hTyskadI0ag54OdjY+nOnxbXfY0sZOwO5gX9UilfvwRgeqAaJoYgVqZL9w8c3nVHHZLtB4h5nUAKuLHUBaqV5d/L+PBM0CrKtLNGXc0zWg6W4UmcN6E9g0O10sDK284dNzicvhCDnZ1LmvLAforhGVgZ0MHiawVjJwvT4GboLtOK1MP+vLzJ/g==
  template:
    metadata:
      name: minio-credentials
      namespace: spark
