# Service cho Spark Connect (clients kết nối vào)
apiVersion: v1
kind: Service
metadata:
  name: spark-connect-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: spark-connect-server
  ports:
    - name: grpc
      port: {{ .Values.connectPort }}
      targetPort: {{ .Values.connectPort }}
    - name: spark-ui
      port: 4040
      targetPort: 4040
    - name: jupyter
      port: 8888
      targetPort: 8888
---
# Headless service cho executor pods giao tiếp với driver
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-headless
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: spark-connect-server
  clusterIP: None
  ports:
    - name: block-manager
      port: 7078
    - name: driver
      port: 2222
