dagster:
  imagePullSecrets: 
    - name: ghcr-secret

  dagster-user-deployments:
    deployments:
      - name: "iris-analysis"
        image:
          repository: "ghcr.io/cukhoaimon/iris_analysis"
          tag: 1
          pullPolicy: Always
        dagsterApiGrpcArgs:
          - "--python-file"
          - "/my_project/definitions.py"
        port: 3030
        includeConfigInLaunchedRuns:
          enabled: true
        env: []

  postgresql:
    postgresqlUsername: test
    postgresqlPassword: test
    postgresqlDatabase: test
