apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iceberg-catalog-data
  namespace: data-warehouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # thêm nếu cluster cần chỉ định