apiVersion: v1
kind: Service
metadata:
  name: iceberg-rest-catalog
  namespace: data-warehouse
  labels:
    app: iceberg-rest-catalog
spec:
  selector:
    app: iceberg-rest-catalog
  ports:
    - name: http
      port: 8181
      targetPort: 8181