apiVersion: v2
name: spark-operator
description: Spark Kubernetes Operator (kubeflow)
type: application
version: 0.1.0
dependencies:
  - name: spark-operator
    repository: https://kubeflow.github.io/spark-operator
    version: "2.1.1"