---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: primary-object-store-credentials
  namespace: data-warehouse
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgB4PiuGAotD+eG3hocJIZFlHjktM0e1BpgITYduXkowCNkJPnifYpT3nM8LfcF1Ppm109aYcgEXi90oNUUCbe43aNfRJYuqyFRxYqNXpu0aeAvS28O0lVPpJb+ZdYPuyIaUfz/5IyZsONzSEoxAtm+K1N7jOHVhWw++pNFYPHBkYSDcf8ZwJ2M+tXFTD0+pZ8u/NdJQN2k4+yRBERzabutRglNl3txlanmV+L0suwtw77TJMy+2UPLqls/bVSDBAwajLkAS5XY/RC0XtPoEMdoodFZ+0dlzXRXa1cA6xqPsA1CpBd9KjaBJpQus7es/ohomj2ek5QCVuDrWXtYGjvjiWtzNdaeQw+42ZzmogZrWs+L/ZH9enFknP/ckJI2HnXD0cXqyC80Kd+NfiwrXI2K/ocilWtCpU1aNbqNxaW4ri9DAllJmC4ZysyYPG9FiHVtn2UNoZDj0gej2uyAVUu7nnzBHoy4diPexe1bJTVFGRRQYaLfHPiHIOS2weoTd1aO2sOLvQsNigOuvTDc9dAU5d2otQ/kgb8sDOJbW/cvrFrIbwOBtmPW74hEYRNB5s3AcLnD8vwaGTnGFi8htNwdkuNoVDjYPLvIcP6vzhvMR0iRzlbFlz1QFRvBLJW7bXpfgayZnnwwOFVlmTwIuj/JqW7xF40EDjcWiwyZmWrNnej22i5FQO6U2BPGnT1XuuG6Rl0Uph282yA==
    MINIO_ROOT_USER: AgBG3LmJeDt1azPb6SOXa91kGLs2YO7pJU1omD9ll3C+fWR8FOtij9qT8CFw5PV4L/dyO6oj3OdRmwmvpwPPBQ6Oj+6r0nD4B9yioJx6FYa4LEK0lTOpa96vRAB/YIZ0BQOZiaERXjhc3NQTuzOXmuRiyjN8ZtYa9gNUfCg8CtrB5Ke60unm2pt6PgL16jio/8JymaUJl1/knB57iP31Q5sAQjSUm4SGVTOWGNDGFS+6qbdb0MF7WM0YOG6U4jNRdp8ZPmfXj5MWuspw8ptjOeuwctFk/JAJwuRcDlAoYoUO3gGwhqEtja2EVuIBdY4LO8H1OjtSkFGZTFaMJLcufI7F3b5JZd/3rGTcUFm78hZheo0eHr0j1jhYgyLLsCh/MenGSY3/Z8qbzEq2ZWTXaFuQ8iTc7WOK8nyY2y9gYNmzeC3/1YgrFLtUhtq9qH/keYRi0k8ufsY6DANXgzkJrpjRjjWukQL6yUJFvF819AeD5EuxFkcKpSz0ilyX5xjA3zqU7BX9KKljsPuns3V+VoiHtqc46QmsVOkpYtL9hAqcTbEaf8l0VgqX3/mUzupIvB081jzcgdWYBnI7gN9V/YWxcOwT4UbGrdXITPW5gqxDS//1IcjPlSb50CoP/Ez3Li3FncIc46uYNiRx06CxCB5jsCKcUE9wP/AqhL25dtF369oN/JYS5LB+E7tJS5pJPwfdMzSugA==
  template:
    metadata:
      name: primary-object-store-credentials
      namespace: data-warehouse
