apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStore.name }}-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  accesskey: {{ .Values.objectStore.credentials.accessKey }}
  secretkey: {{ .Values.objectStore.credentials.secretKey }}
