apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStore.name }}-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.objectStore.credentials.accessKey }}
  MINIO_ROOT_PASSWORD: {{ .Values.objectStore.credentials.secretKey }}
