image:
  repository: quay.io/jupyter/pyspark-notebook
  tag: latest
  pullPolicy: Always

service:
  port: 8888

ingress:
  host: jupyter.local
  ingressClassName: nginx

sparkConnect:
  url: sc://spark-connect-server.spark.svc.cluster.local:15002
