apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-regionserver
spec:
  serviceName: hbase-regionserver
  replicas: {{ .Values.hbase.regionserver.replicas }}
  selector:
    matchLabels:
      app: hbase-regionserver
  template:
    metadata:
      labels:
        app: hbase-regionserver
    spec:
      initContainers:
      - name: wait-master
        image: busybox
        command: ['sh', '-c',
          'until nc -z hbase-master 16000;
           do echo "waiting for Master..."; sleep 3; done']
      containers:
      - name: hbase-regionserver
        image: {{ .Values.hbase.image }}
        command: ["/bin/bash", "-c", "hbase regionserver start"]
        ports:
        - containerPort: 16020
        - containerPort: 16030
        resources: {{- toYaml .Values.hbase.regionserver.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /hbase/conf/hbase-site.xml
          subPath: hbase-site.xml
        - name: rootdir
          mountPath: /data/hbase
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: hbase-config
      - name: rootdir
        persistentVolumeClaim:
          claimName: hbase-rootdir
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.hbase.regionserver.storage }}