apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cukhoaimon/devoops-argocd
    targetRevision: main
    path: dagster
  destination:
    server: https://kubernetes.default.svc
    namespace: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true