apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-hbase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cukhoaimon/devoops-argocd
    targetRevision: HEAD
    path: my-hbase
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
