---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: satellite
spec:
  encryptedData:
    .dockerconfigjson: AgBVTdG9zqy/l6nd6PyrHRY7Bf2Ljko8lgCKmk0Thi+JpmzVy3K90h5/OjzhwFkVdS4Ahl2CkOYMJDq/0Q8HSAQ9yMFSJ0r/fXOLy1JrvWRY9RYmhPk7/ktr0WuURZMuhbGHn59ST5meUYAHGGDDGtGaAcAfFgi9u+9zcmd1omhTuyxrVUzR5jpf08yS8C/nMpXVxRBrnHt8FzTsvFvtRs/u8EXFjki5xGlsCBa9zvhX+U58bNXzAWW3qklgCWZn5GsEVDisuX6u0hAKzuSrR+4LLGnRyBI1sz4ygTx4v5K0VUys1rsilxsZN4mgpRh2HacRhyJP7HjTlc0hNjdun1BWHejwJCucQvhxzIbHGbyBLRSKQuvDUh3lQuCkki+r8PYvXS3bOgRJW8VD+5ygGSw9wEw46B1wAr/y3P5rZotBmcmDvKC/6bmdANZH35JOzhNSM66AV+ljpF2FSizPu87SRIj81jMQIGO1mMMKyoc9kwmxx4GSSoxbJsuOZ76L85tEaU3SZ/+fvCqkcbwZQCdM80S2rai3ZzDKZ6ntwh4kBJ/63K9imIGbowp3WouHNkqfg+e1k/WIMe90UM7Rh/c5yc61/8py06vVzGZx5HB/j0nCrMOdAv46ZUYNOjs+nhl71BaSU0+ybgntC83Wgq+aK2HPzXAAiBBzbgAOyB/07/YAHyJZ3k25S8p5f3ViKOuzQYgwn2Txwxpn5+xWGaITNTYV4BYEVS3FrhwR2w55JcToibGlfxQ7qqOJCLUGjlYmIP04YnBd4zBBd7sqkOPKLD7FsZb5LD8to1u1DwIIpXKp1pRCnbUjI8uBwQcH9tGWEvsCPQGpIY95qPdh4lXjtDuTo2YWf9RT08MCCbd70y1v3+Ev96s7alXNB2geSpzwnW+jNJ04MrMhDlhKVk+yZ2T4iOOJFgQGXCRddIS3u2j73A==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: satellite
    type: kubernetes.io/dockerconfigjson
