apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
  namespace: shared-services
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    {{- range .Values.databases }}
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE USER {{ .user }} WITH PASSWORD '{{ .password }}';
      CREATE DATABASE {{ .name }} OWNER {{ .user }};
    EOSQL
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="{{ .name }}" <<-EOSQL
      GRANT ALL ON SCHEMA public TO {{ .user }};
    EOSQL
    {{- end }}
