objectStore:
  name: primary-object-store
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  pools:
  - name: pool-0
    servers: 1
    volumesPerServer: 1
    size: 10Gi
  services:
    minio:
      serviceType: NodePort
      nodePort: 31000
      consoleNodePort: 31001
