apiVersion: v1 
kind: Service 
metadata:
  name: my-hbase-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-hbase
  ports: 
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: hbase-master
      port: 16000
      targetPort: 16000
    - name: hbase-master-ui
      port: 16010
      targetPort: 16010
    - name: region-server
      port: 16020
      targetPort: 16020
    - name: region-server-ui
      port: 16030
      targetPort: 16030