apiVersion: v1 
kind: Service 
metadata:
  name: my-hbase-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-hbase
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: hbase-master
      port: 60000
      targetPort: 60000
    - name: hbase-master-ui
      port: 60010
      targetPort: 60010
    - name: region-server
      port: 60020
      targetPort: 60020
    - name: region-server-ui
      port: 60030
      targetPort: 60030