apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-hbase-statefulset
spec:
  serviceName: my-hbase-service
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: my-hbase
  template:
    metadata:
      labels:
        app: my-hbase
    spec:
      initContainers:
        - name: copy-config
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - sh
            - -c
            - cp /hbase/conf/* /hbase-conf/ && cp /hbase-config-source/hbase-site.xml /hbase-conf/hbase-site.xml
          volumeMounts:
            - name: hbase-config-source
              mountPath: /hbase-config-source
            - name: hbase-conf-writable
              mountPath: /hbase-conf
      containers:
        - name: hbase
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2181  # ZooKeeper
            - containerPort: 16000 # HBase Master
            - containerPort: 16010 # HBase Master Web UI
            - containerPort: 16020 # RegionServer
            - containerPort: 16030 # RegionServer Web UI
            - containerPort: 8080  # REST API
          volumeMounts:
            - name: hbase-data
              mountPath: /hbase-data
            - name: hbase-conf-writable
              mountPath: /hbase/conf
      volumes:
        - name: hbase-config-source
          configMap:
            name: my-hbase-config
        - name: hbase-conf-writable
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: hbase-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.size }}